name: Check Tweet Action
on:
  push:
    branch:
    - master
    paths:
    - 'tweet/**/*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: matsubara0507/actions/tweet@master
      with:
        consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
        consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
